remote_theme: ziinahzoor/cybersynth-theme

plugins:
  - jekyll-remote-theme
  - jekyll-archives

title: Hopefully a blog
tagline: My public academic diary
description: Academic exploration of different concepts through the eyes of a student.

lang: en
timezone: Europe/Belgrade
url: ""
baseurl: ""
future: true
theme_mode: dark
#pepika
github:
  username: PetrarkaR

social:
  name: Petar
  email: petar35r@gmail.com
  links:
    - https://github.com/PetrarkaR

avatar: /assets/img/avatar/avatar.png

paginate: 10

kramdown:
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: /categories/:name/
